"""
Base Strategy Module

Provides the base classes and data structures for all trading strategies.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Dict, Any, List
from datetime import datetime

import pandas as pd


class Signal(Enum):
    """Trading signal direction"""
    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"


class OrderType(Enum):
    """Order type for execution"""
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


@dataclass
class TradeSignal:
    """
    Represents a trading signal generated by a strategy

    Attributes:
        timestamp: Time when signal was generated
        signal: Direction of the signal (LONG, SHORT, FLAT)
        price: Price at which signal was generated
        stop_loss: Stop loss price
        take_profit: Take profit price
        trailing_stop: Trailing stop distance
        reason: Reason for the signal
        indicators: Dictionary of indicator values at signal time
        quantity: Number of contracts to trade
    """
    timestamp: datetime
    signal: Signal
    price: float
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    trailing_stop: Optional[float] = None
    reason: Optional[str] = None
    indicators: Optional[Dict[str, Any]] = None
    quantity: int = 1

    def __str__(self) -> str:
        sl_str = f", SL={self.stop_loss:.2f}" if self.stop_loss else ""
        tp_str = f", TP={self.take_profit:.2f}" if self.take_profit else ""
        reason_str = f", Reason={self.reason}" if self.reason else ""
        return f"TradeSignal({self.timestamp}, {self.signal.value}, Price={self.price:.2f}{sl_str}{tp_str}{reason_str})"


@dataclass
class Position:
    """
    Represents an open trading position

    Attributes:
        entry_time: Time when position was opened
        entry_price: Price at which position was opened
        quantity: Number of contracts
        direction: Direction of the position (LONG or SHORT)
        stop_loss: Current stop loss price
        take_profit: Take profit price
        trailing_stop: Trailing stop distance (in price units)
    """
    entry_time: datetime
    entry_price: float
    quantity: int
    direction: Signal
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    trailing_stop: Optional[float] = None
    _highest_price: float = field(default=0.0, repr=False)
    _lowest_price: float = field(default=float('inf'), repr=False)

    def __post_init__(self):
        """Initialize tracking prices"""
        self._highest_price = self.entry_price
        self._lowest_price = self.entry_price

    @property
    def is_long(self) -> bool:
        """Check if position is long"""
        return self.direction == Signal.LONG

    @property
    def is_short(self) -> bool:
        """Check if position is short"""
        return self.direction == Signal.SHORT

    def update_trailing_stop(self, current_price: float) -> None:
        """
        Update trailing stop based on current price

        Args:
            current_price: Current market price
        """
        if self.trailing_stop is None:
            return

        # Track highest/lowest prices
        self._highest_price = max(self._highest_price, current_price)
        self._lowest_price = min(self._lowest_price, current_price)

        if self.is_long:
            # For long positions, trail stop up with price
            new_stop = self._highest_price - self.trailing_stop
            if self.stop_loss is None or new_stop > self.stop_loss:
                self.stop_loss = new_stop
        else:
            # For short positions, trail stop down with price
            new_stop = self._lowest_price + self.trailing_stop
            if self.stop_loss is None or new_stop < self.stop_loss:
                self.stop_loss = new_stop


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies

    Provides the framework for implementing trading strategies with:
    - Parameter management
    - Position tracking
    - Trade history
    - Signal generation interface

    Subclasses must implement:
    - prepare_data(): Add required indicators to data
    - generate_signal(): Generate trading signals
    """

    def __init__(self, name: str = "BaseStrategy", params: Dict[str, Any] = None):
        """
        Initialize the strategy

        Args:
            name: Strategy name for identification
            params: Strategy parameters
        """
        self.name = name
        self.params = params or {}
        self.position: Optional[Position] = None
        self.trades: List[Dict[str, Any]] = []

        # Call initialization hook
        self.on_init()

    def on_init(self) -> None:
        """
        Initialization hook for subclasses

        Override this method to perform custom initialization
        """
        pass

    @abstractmethod
    def prepare_data(self, data: pd.DataFrame) -> pd.DataFrame:
        """
        Add required indicators to the data

        Args:
            data: Raw OHLCV DataFrame

        Returns:
            DataFrame with indicators added
        """
        pass

    @abstractmethod
    def generate_signal(
        self,
        data: pd.DataFrame,
        current_idx: int
    ) -> Optional[TradeSignal]:
        """
        Generate trading signal based on current market conditions

        Args:
            data: DataFrame with OHLCV and indicators
            current_idx: Current bar index

        Returns:
            TradeSignal if conditions are met, None otherwise
        """
        pass

    def update(
        self,
        data: pd.DataFrame,
        current_idx: int
    ) -> Optional[TradeSignal]:
        """
        Update strategy with new data and generate signal

        This is the main entry point called by the backtester/live trader

        Args:
            data: DataFrame with OHLCV and indicators
            current_idx: Current bar index

        Returns:
            TradeSignal if conditions are met, None otherwise
        """
        return self.generate_signal(data, current_idx)

    def calculate_position_size(
        self,
        signal: TradeSignal,
        account_value: float,
        risk_per_trade: float,
        point_value: float = 5.0,
        max_contracts: int = 5
    ) -> int:
        """
        Calculate position size based on risk management

        Default implementation uses fixed fractional position sizing.
        Override in subclass for custom sizing logic.

        Args:
            signal: The trade signal
            account_value: Current account value
            risk_per_trade: Fraction of account to risk (e.g., 0.01 for 1%)
            point_value: Dollar value per point
            max_contracts: Maximum allowed contracts

        Returns:
            Number of contracts to trade
        """
        if signal.stop_loss is None:
            return 1

        # Calculate dollar risk per contract
        price_risk = abs(signal.price - signal.stop_loss)
        dollar_risk_per_contract = price_risk * point_value

        if dollar_risk_per_contract == 0:
            return 1

        # Calculate max dollar risk for this trade
        max_dollar_risk = account_value * risk_per_trade

        # Calculate position size
        position_size = int(max_dollar_risk / dollar_risk_per_contract)

        # Apply limits
        position_size = max(1, min(position_size, max_contracts))

        return position_size

    def on_fill(
        self,
        signal: TradeSignal,
        fill_price: float,
        fill_time: datetime
    ) -> None:
        """
        Handle order fill notification

        Args:
            signal: The signal that was filled
            fill_price: Actual fill price
            fill_time: Time of fill
        """
        if signal.signal in [Signal.LONG, Signal.SHORT]:
            self.position = Position(
                entry_time=fill_time,
                entry_price=fill_price,
                quantity=signal.quantity,
                direction=signal.signal,
                stop_loss=signal.stop_loss,
                take_profit=signal.take_profit,
                trailing_stop=signal.trailing_stop
            )

    def on_exit(
        self,
        exit_price: float,
        exit_time: datetime,
        reason: str
    ) -> None:
        """
        Handle position exit

        Args:
            exit_price: Price at which position was closed
            exit_time: Time of exit
            reason: Reason for exit
        """
        if self.position:
            # Record the trade
            trade_record = {
                'entry_time': self.position.entry_time,
                'exit_time': exit_time,
                'entry_price': self.position.entry_price,
                'exit_price': exit_price,
                'quantity': self.position.quantity,
                'direction': self.position.direction.value,
                'reason': reason
            }
            self.trades.append(trade_record)

            # Clear position
            self.position = None

    def reset(self) -> None:
        """Reset strategy state"""
        self.position = None
        self.trades = []
        self.on_init()
